name: Deploy CNN Video Timer to ZR'S VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} zhurong@74.48.63.73 <<'ENDSSH'
        cd /opt/cnnvideo-timer && git pull
        ENDSSH
